name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/carregamento.png
    - assets/images/logo.png
    - assets/images/tom.png
    - assets/images/lar.png
    - assets/images/alimentacao.png

  fonts:
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf 
